//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesa
    {
        public mesa()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int Id { get; set; }
        public int num_mesa { get; set; }
        public int capacidad { get; set; }
    
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
